In [4]:
import numpy as np

In [5]:
# 均匀分布
np.random.rand(10000)

#高斯分布
np.random.randn(10000)


array([ 0.43271547, -0.79273386,  0.54289423, ...,  0.4651911 ,
       -0.24946503, -2.32166511])

In [6]:
tmp=np.random.randn(10000)
print(tmp)

[-0.24813173 -0.07847523 -1.91311886 ...  0.01095526 -0.14153857
  0.1985707 ]


In [7]:
print(np.sum(tmp<0))

4928


In [8]:
print(np.sum(tmp>0.5))

3088


In [9]:
print(np.sum(tmp>3))

11


In [10]:
dots=np.random.rand(1000000,2)
print(dots)

[[0.09163085 0.91649703]
 [0.45094612 0.9156575 ]
 [0.40452777 0.89986448]
 ...
 [0.44580857 0.80516346]
 [0.34337503 0.99434191]
 [0.07646172 0.17069092]]


In [11]:
np.min(dots)

3.5631293571203315e-07

In [12]:
radii=np.sqrt(dots[:,0]**2+dots[:,1]**2)
print(radii)

[0.92106624 1.02067676 0.98660975 ... 0.92034421 1.05196114 0.18703418]


In [13]:
print(np.sum(radii<=1))

785811


In [14]:
print(np.pi/4)

0.7853981633974483


In [15]:
np.pi


3.141592653589793